name: Update Civic-Lib API Docs

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3am UTC
  workflow_dispatch:

jobs:
  update-api-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [
          civic-interconnect-lib,
          civic-lib-boundaries,
          civic-lib-geo,
          civic-lib-ocd,
          civic-lib-snapshots,
          civic-lib-ui
        ]

    steps:
      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v4
        with:
          repository: civic-interconnect/${{ matrix.repo }}
          path: repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install deps if available
        working-directory: repo
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements-dev.txt ]; then
            python -m pip install --upgrade -r requirements-dev.txt
          else
            echo "No requirements-dev.txt found, continuing..."
          fi

      - name: Run dev_generate_api.py if available
        working-directory: repo
        run: |
          if [ -f dev_generate_api.py ]; then
            python dev_generate_api.py
          else
            echo "No dev_generate_api.py found, skipping."
          fi

      - name: Commit changes if needed
        working-directory: repo
        run: |
          git config user.name "Civic Interconnect Bot"
          git config user.email "ci@civic-interconnect.org"
          git add meta/api.md || true
          git commit -m "Daily API doc update" || echo "No changes"
          git push || echo "Nothing to push"
